CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL, title VARCHAR(200) NOT NULL,
  description TEXT, status VARCHAR(20) DEFAULT 'TODO', priority VARCHAR(10) DEFAULT 'medium',
  created_at TIMESTAMP DEFAULT NOW()
);